# Generated by Django 3.1.4 on 2020-12-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_1_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_1_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slot_2_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_2_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slot_3_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_3_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slot_4_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_4_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slot_5_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_5_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slot_6_dex_id', models.IntegerField(blank=True, max_length=150, null=True)),
                ('slot_6_name', models.CharField(blank=True, max_length=150, null=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer')),
            ],
        ),
    ]
