# Generated by Django 3.1.4 on 2020-12-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201229_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='slot_1_dex_id',
            new_name='slot_1_national_dex_id',
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_1_type_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_2_type_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_3_type_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_4_type_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_5_type_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_move_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_move_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_move_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_move_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_primary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_secondary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_species',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='slot_6_type_weight',
            field=models.IntegerField(null=True),
        ),
    ]
