# Generated by Django 3.1.4 on 2021-01-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210103_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_1_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_1', to='teams.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_2_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_2', to='teams.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_3_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_3', to='teams.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_4_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_4', to='teams.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_5_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_5', to='teams.pokemon'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slot_6_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_6', to='teams.pokemon'),
        ),
    ]
